version: "3.9"
services:
  devcontainer: 
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      args:
        USER_NAME: ${USER}
        USER_ID: ${USER_ID}
        USER_SHELL: ${SHELL}
    volumes:
      - "${HOME}:/home/${USER}"