version: "3.9"
services:
  devcontainer: 
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      args:
        USER_NAME: ${USER}
        USER_ID: ${USER_ID}
    volumes:
      - "${HOME}/.ssh:/home/${USER}/.ssh"
    env_file:
      - .devcontainer/devcontainer.env